# Generated by Django 5.2.3 on 2026-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'ordering': ['display_order', 'starts_at', 'name']},
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='colour_tag',
            field=models.CharField(default='#047c78', max_length=7),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='description',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
