events {}

http {
  upstream meal_registry_app {
    server webapp1:3000;
    server webapp2:3001;
  }

  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    client_max_body_size 10m;

    location /static/ {
      alias /staticfiles/;
    }

    location /media/ {
      alias /media/;
    }

    location / {
      proxy_pass http://meal_registry_app;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
